; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter, extra scripting
;   Upload options: custom port, speed and extra flags
;   Library options: dependencies, extra library storages
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-supermini]
platform = espressif32
board = dfrobot_firebeetle2_esp32s3
framework = arduino

#upload_port = COM6
monitor_speed = 115200

; ESP32-S3 Super Mini 使用 USB 串口
build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
    -DFASTLED_ALLOW_INTERRUPTS=1

lib_deps = fastled/FastLED
